spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/mathdb"
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog.sql
    enabled: true